### ISSUE TITLE
'dict' object has no attribute 'has_key'

### ISSUE THREAD

**Issue by bradybray** [calendarific/python-calendarific#1]
```
\__init__.py in holidays(self, parameters)
     11         url = 'https://calendarific.com/api/v2/holidays?'
     12
---> 13         if parameters.has_key('api_key') is False:
     14             parameters['api_key'] = self.api_key
     15

AttributeError: 'dict' object has no attribute 'has_key'
```

Not sure where you're getting the method you're trying to call but its not working. I tried calling it in the same scope as the call to instantiate the API. I followed the directions on the site as specified. 

Please advise.

**Comment by mer0mingian** [comment]
Can confirm this issue on Python 3.6.
Supposed change would be to change to 
`if parameters.get('api_key') is not None: 
...`

**Comment by faisaltheparttimecoder** [comment]
@mer0mingian, got the same problem and I use Python 3.7.x, `has_key` was removed from python 3.x, 

@ryan-cal I have placed a pull request (https://github.com/calendarific/python-calendarific/pull/2) which will fix this issue , let me know if you have any questions

**Comment by ryan-cal** [comment]
@faisaltheparttimecoder PR is merged in now. Closing this issue.

**Comment by kevindesmidt-cure** [comment]
I am still getting this error and I have just installed the latest python-calendarific library ??
